version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    python:
      patterns:
        - "*"
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    rust:
      patterns:
        - "*"
