name: publish-versions

on:
  push:
    tags:
      - '[0-9]+'
  release:
    types: [published]

jobs:
  publish-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed Python distributions
        id: changed
        uses: ./.github/actions/changed-distributions
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Release
        if: steps.changed.outputs.changed == 'true'
        run: |
          for dist in ${{ steps.changed.outputs.distributions }}; do
            gh release upload ${{ github.ref_name }} "$dist" --clobber
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push version files
        if: github.event.release.prerelease == false
        run: |
          #!/bin/bash
          set -e

          VERSION=${{ github.ref_name }}
          VERSION_MAJOR=$(echo $VERSION | cut -d. -f1)

          # Create the version file
          mkdir -p version
          echo $VERSION > "version/python-${VERSION_MAJOR}-x86_64-linux-gnu"

          # Create the latest version file
          mkdir -p latest-release
          echo $VERSION > "latest-release/latest-release.json"

          # Commit and push
          git config user.name "Gregory Szorc"
          git config user.email "gregory.szorc@python-build-standalone.com"
          git add version latest-release
          git diff --cached --quiet || git commit -m "$VERSION"
          git push
